apiVersion: apps/v1
kind: Deployment
metadata:
  name:  my-deployment
  labels:
    name:  my-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: myapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image:  nginx:1.17.1
        name:  nginx
        ports:
          - containerPort: 80
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          periodSeconds: 10
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 60m
            memory: 150Mi
          limits:
            cpu: 200m
            memory: 150Mi

